"""empty message

Revision ID: 413576e8b72f
Revises: d2d703214b1e
Create Date: 2020-08-06 13:47:53.453560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413576e8b72f'
down_revision = 'd2d703214b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'passed')
    # ### end Alembic commands ###
