"""Table test

Revision ID: 4c7a7f704600
Revises: 940b17b555d9
Create Date: 2020-04-13 23:08:15.791470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c7a7f704600'
down_revision = '940b17b555d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dictionaries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'mistakes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'mistakes', 'words', ['word_id'], ['id'])
    op.drop_column('mistakes', 'id')
    op.create_foreign_key(None, 'words', 'dictionaries', ['dictionary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.add_column('mistakes', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'mistakes', type_='foreignkey')
    op.drop_constraint(None, 'mistakes', type_='foreignkey')
    op.drop_constraint(None, 'dictionaries', type_='foreignkey')
    # ### end Alembic commands ###
