"""empty message

Revision ID: bbe84c443725
Revises: be0d74508d11
Create Date: 2020-04-22 20:12:10.677774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe84c443725'
down_revision = 'be0d74508d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dictionaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dictionaries', type_='foreignkey')
    op.drop_column('dictionaries', 'user_id')
    # ### end Alembic commands ###
