"""empty message

Revision ID: d2d703214b1e
Revises: 1862ed55762d
Create Date: 2020-08-04 16:01:39.182523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2d703214b1e'
down_revision = '1862ed55762d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('user_answer', sa.String(length=32), nullable=True))
    op.drop_column('test', 'userAnswer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('userAnswer', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('test', 'user_answer')
    # ### end Alembic commands ###
